### ISSUE TITLE
There is no utils dir?

### ISSUE THREAD

**Issue by 96jhwei** [mkang315/RCS-YOLO#1]
I cannot find the "utils" dir. Could you update the codes and add it?

**Comment by mkang315** [comment]
Sorry for bugs. Please download the updated source code.

**Comment by 96jhwei** [comment]
Thanks! There is still a bug. There is no “VoVSR” in the updated yolo.py

Cheers

发件人: mkang315 ***@***.***>
发送时间: 2023年8月1日 16:20
收件人: mkang315/RCS-YOLO ***@***.***>
抄送: 韦家弘 ***@***.***>; Author ***@***.***>
主题: Re: [mkang315/RCS-YOLO] There is no utils dir? (Issue #1)


Sorry for bugs. Please download the updated source code.

**Comment by mkang315** [comment]
Fixed. Please write your comments in the same issue.

**Comment by 96jhwei** [comment]
Thanks!

发件人: mkang315 ***@***.***>
发送时间: 2023年8月1日 16:42
收件人: mkang315/RCS-YOLO ***@***.***>
抄送: 韦家弘 ***@***.***>; Author ***@***.***>
主题: Re: [mkang315/RCS-YOLO] There is no utils dir? (Issue #1)


Fixed. Please write your comments in the same issue.
