### ISSUE TITLE
A videographic Demonstration on how to execute the code

### ISSUE THREAD

**Issue by Buvan4422** [mkang315/RCS-YOLO#9]
Hello, 
I have executed the code many times but I still can't figure out where I am going wrong. When I run train.py it creates runs/exp/weights, but there are no best.pt and las.pt files in that. Please help me on how to execute the code from scratch

**Comment by mkang315** [comment]
Thank you for using RCS-YOLO. Your training process failed or didn't finish if there were not best.pt and last.pt. I suggest you search for answers from https://github.com/WongKinYiu/yolov7/issues and ask them how to solve them. Someone also had problems like yours, for example:

In Yolo v7, how do you get best.pt? I only found init and last.pt.
https://github.com/WongKinYiu/yolov7/issues/1910
the best.pt and last.pt is the same!!!
https://github.com/WongKinYiu/yolov7/issues/1114

**Comment by Buvan4422** [comment]
Thank you for the response. The code have executed and I have resolved the errors.
